### PR TITLE
[WIP] basics

### PR DESCRIPTION
**Pull request by bast**
Work in progress.

### CODE REVIEW

**Comment by bast** [comment]
Thanks but it was work in progress (WIP) - not meant to be merged yet, but out there for comments. But no problem - I will open a new one.

**Comment by Sabryr** [comment]
Easier to review if pull requests are small, and obvious changes can be easily merged.

**Comment by bast** [comment]
I totally agree. At least I try to make the commit messages small and well defined so that you can browse only those. I will try to make PRs as fine-grained as possible but it is a trade-off with respect to me waiting and accumulating conflicts.

**Comment by Sabryr** [comment]
I learned that from you, so I see no way out for you in this.

**Pull request merged**
