### PR TITLE
Show link to quick reference and show episode durations instead of start times

### PR DESCRIPTION
**Pull request by bast**

### CODE REVIEW

**Comment by Sabryr** [comment]
Isn't start time better for time time management ? You get a better understanding whether falling behind too much

**Comment by bast** [comment]
See discussion in the chat. You might be right.

My counter arguments:
- even though we had start times in the past, we had a lot of bad time management in the past (this does not mean that the new scheme will work better)
- durations instead of start times makes it easier to move lesson without adapting the start time
- my feeling is that start times encourage instructors to teach episodes exactly in this order and to follow the schedule but I would prefer if instructor manage their time and decide which episodes to teach or skip
-  if we have start times and we don't manage to present something, participants may feel like they missed out - my hope is that the durations allow for more flexibility

**Comment by Sabryr** [comment]
OK, Is it OK if we do it after tomorrow, as I have planed this already.

**Comment by rkdarst** [comment]
I agree with durations instead of start times... start times is nice if we are orchestrating a whole workshop, but since we move lessons around a lot we keep having to change them.  Or at least we should move around more.

If we make sure each lesson starts on an even hour then it's a bit easier to also manage time.

On the coderefinery.org lesson listing we could tag each lesson with its duration to make planning easier.

**Comment by bast** [comment]
> OK, Is it OK if we do it after tomorrow, as I have planed this already.

There is no pressure or expectation to merge last-minute changes.

The only slight disadvantage for you of not merging is that you will not see a link to a quick reference. I had to package it into the same PR since it references the same submodule. But this is something new anyway that Richard wrote and from my perspective it can wait.

I agree that we need overall timings on the workshop page - I will open an issue on that on the website repo.

**Comment by bast** [comment]
Merging.

**Pull request merged**
