### PR TITLE
display link to reference.md

### PR DESCRIPTION
**Pull request by bast**
As discussed in https://github.com/coderefinery/jekyll-common/issues/4

### CODE REVIEW

**Comment by rkdarst** [comment]
The jekyll is magic to me, but looks good.  Thanks for figuring this out!

**Comment by rkdarst** [comment]
I just got an email about a page build failure.  Did you as well?

```
The page build failed for the `gh-pages` branch with the following error:

The tag `file_exists` on line 8 in `jekyll-common/includes/navigation.html` is not a recognized Liquid tag. For more
information, see https://help.github.com/en/articles/page-build-failed-unknown-tag-error.
```

**Comment by bast** [comment]
I got it too but could not react until now - very sorry for this. It worked locally. If you like, I can send a new PR which assumes `reference.md` is always there. It's fine for other repos since they are "behind".

**Comment by rkdarst** [comment]
It's up to you.  The reference.md doesn't have much yet and is
probably better to not have, than have a bad one.  I'd say focus
efforts on more important things for now.

**Comment by bast** [comment]
OK

**Pull request merged**
