### PR TITLE
Improve 02basics

### PR DESCRIPTION
**Pull request by Sabryr**
To evaluate

### CODE REVIEW

**Comment by wikfeldt** [comment]
i like this a lot! good to create a mind model before moving on to the commands

**Comment by bast** [comment]
Yes this is super good. Like also the focusing analogy.

**Comment by Sabryr** [comment]
Thank you. I was trying to find a good analogy for days. Glad someone else liked it. Any comments on the Diagrams ?

**Comment by bast** [comment]
I like the graphics a lot. I would only remove the ">" in ">git". I think it is not needed. In the rest of the material we use "$" but IMO we can leave it out to avoid confusion about what that part means.

**Comment by Sabryr** [comment]
OK. I will edit the image and send a pull request

**Pull request merged**
