### PR TITLE
content/exercises: Add exercies list directive

### PR DESCRIPTION
**Pull request by rkdarst**
- sphinx-lesson with the feature is now released
- note: virtualenvs will need to be rebuilt.
- Review:
  - Check the preview and make sure it looks good
  - CI check

### CODE REVIEW

**Comment by bast** [comment]
Can you remind me where I can check the preview?

**Comment by rkdarst** [comment]
https://coderefinery.github.io/git-intro/branch/rkdarst--exercise-list-2/exercises/

(an action developer should make something that comments this on every PR)

**Comment by bast** [comment]
And this would then invalidate #327 right?

**Comment by rkdarst** [comment]
Correct, this replaces the previous demo that used the unreleased version

**Pull request merged**
