### PR TITLE
Avoid creating a README and add change to the ingredients and then re…

### PR DESCRIPTION
**Pull request by Sabryr**
Related to issue #179. I am changing all episodes to be constant with thsi

### CODE REVIEW

**Comment by bast** [comment]
I would not change the past hashes since they are used also in later episodes to keep consistency in case somebody compares the hashes. For the participants they will be different anyway.

**Comment by Sabryr** [comment]
Plan is to change all episodes consitantly.  If they do compare hashes across lessons I think a bigger issue would be what happened to the README, number of commits and what happened to the revert hash . To do the revert in another branch possible, but it is too early for branches.

**Comment by bast** [comment]
It should also be consistent with this: https://github.com/coderefinery/recipe
Then there is also this: https://github.com/coderefinery/guacamole (I am not sure why both exist).

**Comment by bast** [comment]
Please git grep whether both are used. I would remove one of them. Also no need to make everything super consistent also with reality (may not be possible), but I would not change hashes that do not need changing and it's OK to "invent" hashes since on participant's computers they will be different anyway. Just when they clone our recipe they might expect same past hashes.

**Comment by bast** [comment]
This PR contains unrelated changes from another PR. I recommend to rebase these changes to get rid of the unrelated changes.

**Comment by Sabryr** [comment]
> This PR contains unrelated changes from another PR. I recommend to rebase these changes to get rid of the unrelated changes.

This is fixed (still WIP)

**Comment by Sabryr** [comment]
Not easy to make this sort of change, we need to investigate some sort of config file based approach for this kind of refracting.

**Comment by bast** [comment]
See my comment in chat - it is not clear to me yet why so much had to be changed. I was expecting that we show the revert on top of the existing example.

**Comment by bast** [comment]
In other words I was expecting maybe 1-2 commits to be added but now there are many changes in many places. Possibly I am missing something and misunderstanding can be on my side.

**Comment by bast** [comment]
Aha - it seems you want the reverts to be visible also in later episodes. In my opinion this was not necessary. We could have instead shown how to revert a commit and if then removed the revert and continued with a simpler example for the following episodes without changing anything but of course I respect if you prefer to have a consistent git graph but it crates/created more work for you and I am unsure whether it will help or complicate the graphs.

**Comment by bast** [comment]
My personal recommendation is to not carry the revert commit into the branching/merging episode: it's a lot of work to do this consistently and it will complicate graphs, IMO unnecessarily.

Bonus of not carrying the commits: we can show both revert and reset one after another.

**Pull request closed without merging**
