### PR TITLE
Add a section at the end to clean the experiments with the repo

### PR DESCRIPTION
**Pull request by Sabryr**
Concerns the issue #179

### CODE REVIEW

**Comment by bast** [comment]
I agree. If you like you can show: revert, followed by soft reset, followed by hard reset.

**Comment by Sabryr** [comment]
Included only the hard reset, I think we can leave the --soft for later

**Comment by bast** [comment]
That's fine, I can add the soft step for a later workshop in a later PR - I think it would be a nice progression:
- revert: see we got a new commit
- soft reset: see commit is gone but changes are staged
- hard reset: changes are gone also

**Comment by bast** [comment]
It's still marked "draft" though but from the title rename I understand it's ready for review?

**Comment by Sabryr** [comment]
Yes, now ready

**Comment by bast** [comment]
Thanks for the change and your understanding and patience with my questions.

**Pull request merged**
