### PR TITLE
add missing instruction to switch branches

### PR DESCRIPTION
**Pull request by coandrei**
Enhancement to the [create and commit branches exercise](https://coderefinery.github.io/git-intro/06-branches/#exercise-create-and-commit-to-branches)
The work is carried out in the `less-salt` branch.
Then, the text and the output of the `git branch` indicate that the pointer is to the `experiment` branch.
Thus, an instruction to switch branches is needed. 
`git checkout experiment`
Only after this step `git branch` returns
```shell
* experiment
  less-salt
  master
```

### CODE REVIEW

**Comment by bast** [comment]
Thanks a lot! But I am wondering whether we should not rather change the output and the image and not add that extra step? I am happy to help with the latter but what would in your opinion be most useful and least confusing for learners? Because after that step we don't really use that branch but again switch to another branch.

**Comment by coandrei** [comment]
Indeed. That is another way to solve it. In this case, everything what comes after must be changed:
`git branch`
`git graph`
and the visual representation depicted by the [figure](https://coderefinery.github.io/git-intro/img/gitink/git-branch-2.svg)

My initial proposal aimed to bring the least changes possible to the code. 
Your alternative maintains the logical flow of the story though. 
Thus, it might be favored from the learning perspective.

**Comment by coandrei** [comment]
I am not sure how to change the initial patch. Thus, I put here the output for the two git commands 
They have been corrected manually since the hash tags must come from the same repo in order to ensure consistency in the entire page. Please double check.

```
$ git branch

  experiment
* less-salt
  master


$ git graph

* bf59be6 (HEAD -> less-salt) reduce amount of salt
| * 6feb49d (experiment) maybe little bit less cilantro
| * 7cf6d8c let us try with some cilantro
|/
* dd4472c (master) we should not forget to enjoy
* 2bb9bb4 add half an onion
* 2d79e7e adding ingredients and instructions
```

The visual image must be changed also accordingly.

**Comment by bast** [comment]
Thanks a lot for this! I will very soon follow by updating the figure.

**Comment by bast** [comment]
Thank you!

**Comment by bast** [comment]
Really great that you fixed this.

**Pull request merged**
