### PR TITLE
Merge git-solo to git-intro

### PR DESCRIPTION
**Pull request by Sabryr**
I have played git-solo from the tip of git-intro. All commits of both repos are intact. Following tag was attached to the point where both met.
git tag -a Starting-git-solo 58c3a53

### CODE REVIEW

**Comment by bast** [comment]
I would change the PR title - since we are not merging to solo but to intro. Also the last commit message "After the merger with Git-solo" does not describe what is in the commit.

**Comment by wikfeldt** [comment]
thanks Sabry! What's happening in the last commit, looks like all the episodes are new

**Comment by bast** [comment]
I am not sure why we need any commits after 2345a77.

**Comment by bast** [comment]
Or to be more clear: why does the PR contain commits after the last commit on git solo?

**Comment by Sabryr** [comment]
There are commits after last commit of git-solo because conflicts were resolved. e.g. with _config.yml

**Comment by bast** [comment]
Among all my annoying questions one thing should not get lost: thanks so much for doing this!

**Comment by Sabryr** [comment]
I do not mind the questions, combining repositories not some thing I do everyday (rather not something I want to do). A better commit message would have avoid the questions anyway

**Comment by bast** [comment]
I am still unsure why there were conflicts if the git solo stuff all happened after the git intro work?

**Comment by Sabryr** [comment]
Modifications that can not be merged due to unrelated histories.

Here are the conflicts and some reasons:
 * branch            gh-pages   -> FETCH_HEAD
Auto-merging index.md
CONFLICT (add/add): Merge conflict in index.md
Auto-merging _episodes/05-undoing.md
CONFLICT (add/add): Merge conflict in _episodes/05-undoing.md
Auto-merging _config.yml
CONFLICT (add/add): Merge conflict in _config.yml
Auto-merging README.md
CONFLICT (add/add): Merge conflict in README.md
Auto-merging .gitignore
CONFLICT (add/add): Merge conflict in .gitignore
Automatic merge failed; fix conflicts and then commit the result.
------

----
 _config.yml

fork_me_ribbon_url: The URL is different https://github.com/coderefinery/git-intro Vs  https://github.com/coderefinery/git-solo
<<<<<<< HEAD
fork_me_ribbon_url: https://github.com/coderefinery/git-intro
title: "Git introduction"
=======
fork_me_ribbon_url: https://github.com/coderefinery/git-solo
title: "Git for the solo developer"
>>>>>>> 2345a77e1d0117ac421b543eb2b3d18fe6c8d8e8
start_time: 570  # 9:30



---

index.md  -  Modifications that can not be merged due to unrelated histories. 
E.g.
<<<<<<< HEAD
Our general flow is 30 minutes on "why version control" and exploring an
online repository to see the full reason we go through this effort.  Then,
there's about an hour of the basics of how to make commits.  Then, there are
several small steps until we get to branching, merging, and conflict
resolution.  Then, we just see a little bit about mirroring to an online
repository and a few other random points before we conclude.
=======
Our general flow is 10 minutes on "why version control", followed by
about 45 minutes of the basics of how to make commits.  Then, there are
several small steps until we get to branching, merging, and conflict
resolution.
Then, we see a little bit about sharing repositories online, how to
effectively dig into the history of a project,
and a few other random points before we conclude.
>>>>>>> 2345a77e1d0117ac421b543eb2b3d18fe6c8d8e8

**Comment by bast** [comment]
OK - I will try this also locally just so I better understand the problem.

**Comment by bast** [comment]
Can we reduce the last 3 commits after 2345a77 to one commit with a clear message?

**Comment by wikfeldt** [comment]
merging #148 instead of this one, but valuable git lessons learned!

**Pull request closed without merging**
