### PR TITLE
fix rendering of "--"; closes #331

### LINKED ISSUE #331: staging area episode - missing dash in soft and staged options (typo)
In the https://coderefinery.org/git-intro/staging-area/#staging-area-commands episode, `git reset –soft HEAD~1` should be `git reset -–soft HEAD~1 ` and `git restore –staged` should be `git restore –-staged` - occurring in the lines below the second and third tree graphs. Possibly a typo introduced by Markdown due to the choice of bold.

### PR DESCRIPTION
**Pull request by bast**

### CODE REVIEW

**Comment by rkdarst** [comment]
Does this work?  I guess probably.

I settled on "always using literal text for commands".  This is quite a common thing to come up!

**Comment by rkdarst** [comment]
We could set `smartquotes = False` in sphinx.conf.  I am not necessarily proposing that we do this, but I just realized it would be an option:
https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-smartquotes

(tldr: yes, merge this, consider long-term plan later)

**Comment by bast** [comment]
It works but I did not expect it to work. I made a typo and it worked. What I hoped that would work, didn't work: `\-\-`. So I don't know why it works but it works :-)

**Comment by bast** [comment]
I can also switch to code block format but it looks ugly in a bold heading. But it does not have to be bold.

**Pull request merged**
