### PR TITLE
Modify 04 branches

### PR DESCRIPTION
**Pull request by Sabryr**
Adding an introduction part to introduce branches. This section will also should maintain the continuation from the previous section.

### CODE REVIEW

**Comment by Sabryr** [comment]
I would like to simplify the section bit more, but do not think will have enough time. May be for the next workshop.

**Comment by Sabryr** [comment]
May be a drastic move, but I removed assignments in the breaks. Break is a break

**Comment by bast** [comment]
Thumbs up! :-) For the graphics: in case you have generated from svg (Inkscape?), I recommend to rather serve svg instead of png since the former is easier to modify in future.

**Comment by Sabryr** [comment]
I would very much like to use SVG as it is less work for me as well. But could not figure out hot to set image size in markup. Tried several things Google said, nothing worked. 
E.g.

**Comment by bast** [comment]
If you want to set image size, use regular HTML  tag. It will be understood. It's really better to use SVG.

**Comment by Sabryr** [comment]
ACK

**Comment by bast** [comment]
I will merge. There is at least one typo: "defualt". On vim, use `:set spell`.

**Pull request merged**
